// Angular/adota/src/app/app.component.ts
import { Component } from '@angular/core';
import {ApiService } from './api.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'adota';

  dogs = [
    {"nome": "Bob", "info": "Cachorro amigavel !", "img": null},
    {"nome": "Billy", "info": "Me adota pf", "img": null}
  ]
  show = false;

  constructor(private apiService: ApiService) { }

  ngOnInit(): void {
    for (let index = 0; index < this.dogs.length; index++) {
      this.apiService.getImgs().subscribe((data) => {
        this.dogs[index].img = data['message'];
      })      
    }
  }

  showModal(){
    this.show = !this.show;
  }
  removerDog(date: any){
    const aux = this.dogs;
    aux.splice(date, 1);
    this.dogs = aux;
    console.log(this.dogs);
  }

  addDog(date: any){
      console.log(date)
      const aux = this.dogs;
      aux.push({"nome": date.nome, "info": date.desc, "img": date.url});
      this.dogs = aux;
  }
}

<style>
  .logo {
    margin-top: 1% !important; 
    margin-right: 5% !important;
  }
  
  .App{
    text-align: center;
  }
  
  .navbar {
    display: block !important;
    text-align: center;
    background-color: beige;
  }
  
  .App-header {
    background-image: linear-gradient(rgba(255,255,255,0.5), rgba(255,255,255,0.5)), url("../assets/banner.jpg");
    background-size: 100%;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    font-size: calc(10px + 2vmin);
    color: black;
  }
</style>

<nav class="navbar navbar-expand-md navbar-dark fixed-top">
  <a class="navbar-brand" href="#"><img class = "logo" src="../assets/logo.png" alt="logo" width="250" height="150">  </a>
  <button class="navbar-toggler hidden-sm-up" type="button" aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

<header class="App-header">
  Plataforma dedica a fazer os doguinhos mais felizes !!!!
  <br/>
  <button type="submit" class="btn btn-success" (click)="showModal()">Cadastrar</button>
</header>

<div class="row">
  <div *ngFor="let dog of dogs; let i = index" class="col-sm-4">
    <app-cards [nome]="dog.nome" [desc]="dog.info" [url]="dog.img" [index] = "i" (delete)="removerDog($event)"></app-cards>
  </div>

  <div *ngIf="show === true">
    <app-cadastro (cadastrar)="addDog($event)"></app-cadastro>
  </div>
</div>

// Svelte/adota/src/App.svelte
<script>
	import Card from './Card.svelte'
	import Cadastro from './Cadastro.svelte'
	import { onMount } from 'svelte';

	let dogs = [
        {"nome": "Bob", "info": "Cachorro amigavel !", "img": null},
        {"nome": "Billy", "info": "Me adota pf", "img": null}
	  ]

	let photos;
	let show;

	function cadastrar(event) {
		console.log(event)
      const aux = dogs;
      aux.push({"nome": event.detail.nome, "info": event.detail.desc, "img": event.detail.img});
      dogs = aux;
    }

	function showModal(){
      show = !show;
 	}
	
	onMount(async () => {
	  dogs.forEach(async (item) => {
		const res = await fetch(`https://dog.ceo/api/breeds/image/random`);
		photos = await res.json();
		item.img = photos.message;
		dogs = dogs
		});
	});

	function removerDog(event){
          const aux = dogs;
          aux.splice(event.detail, 1);
          dogs = aux;
	}

</script>

<main>
	<nav class="navbar navbar-light bg-light">
		<a class="navbar-brand" href="#">
		  <img src="/logo.png" width="250" height="150" alt="" loading="lazy">
		</a>
	  </nav>
	  <header class="App-header">
		<p >
		Plataforma dedica a fazer os doguinhos mais felizes !!!!
		<br/>
		<button type="button" class="btn btn-success" on:click={showModal}>Cadastre</button>
	</p>
	</header>
	<div class="row row-cols-3">
		{#each dogs as dog, index}
				<div class="col">
					<Card nome={dog.nome} index={index} desc = {dog.info} img ={dog.img} on:adocao2={removerDog}/>
				</div>
		{/each}
	</div>

	{#if show === true}
    <Cadastro on:cadastrar={cadastrar}></Cadastro>
  {/if}

</main>

<style>

.navbar {
  display: block !important;
  text-align: center;
}

.App-header {
  background-image: linear-gradient(rgba(255,255,255,0.5), rgba(255,255,255,0.5)), url("/banner.jpg");
  background-size: 100%;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  color: black;
  text-align: center;
}
</style>
