// Angular/adota/src/app/cadastro/cadastro.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import {ApiService } from '../api.service';

@Component({
  selector: 'app-cadastro',
  templateUrl: './cadastro.component.html',
  styleUrls: ['./cadastro.component.scss']
})
export class CadastroComponent implements OnInit {

  url: string;
  @Output() cadastrar: EventEmitter<any> = new EventEmitter<any>();

  constructor(private apiService: ApiService) { }



  ngOnInit(): void {
    this.apiService.getImgs().subscribe((data) => {
      this.url = data['message'];
    })   
  }

  ngAfterViewInit(){
    document.getElementById("modalCadastro").style.display = "none";
    document.getElementById("modalCadastro").click();
  }

  cadastro(nome, desc){
    this.cadastrar.emit({nome:nome, desc:desc, url: this.url});
  }

}

<button type="button" id="modalCadastro" class="btn btn-primary" data-toggle="modal" data-target="#modalC">
    {{modal}}
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="modalC" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Cadastre o cachorro</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="form-group">
          <label for="exampleFormControlInput1">Nome</label>
          <input type="input" class="form-control" #nome id="exampleFormControlInput1" placeholder="Insira o nome">
        </div>
        <br/>
        <div class="form-group">
          <label for="exampleFormControlTextarea1">Descrição</label>
          <textarea class="form-control" id="exampleFormControlTextarea1" #desc rows="5" placeholder="Fale sobre ele"></textarea>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
          <button type="button" class="btn btn-primary" data-dismiss="modal" (click)="cadastro(nome.value, desc.value)">Cadastrar</button>
        </div>
      </div>
    </div>
  </div>

// Svelte/adota/src/Cadastro.svelte
<button type="button" id="cadastroModal" class="btn btn-primary" data-toggle="modal" data-target="#cModal">
    Launch demo modal
  </button>
  
  <div class="modal fade" id="cModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="display:block">
          <h5 class="modal-title" id="exampleModalLabel">Cadastrar Cachorro</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <div class="form-group">
            <label for="exampleFormControlInput1">Nome</label>
            <input bind:value={nome} type="input" class="form-control" id="exampleFormControlInput1" placeholder="Insira o nome">
          </div>
          <br/>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Descrição</label>
            <textarea bind:value={desc} class="form-control" id="exampleFormControlTextarea1" rows="5" placeholder="Fale sobre ele"></textarea>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" on:click={cadastro} data-dismiss="modal">Cadastrar</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
import { onMount } from 'svelte';
import { createEventDispatcher } from 'svelte'

export let nome = ""
export let desc = ""
let photos;
let img;

 const dispatcher = createEventDispatcher()

 onMount(async () => {
		const res = await fetch(`https://dog.ceo/api/breeds/image/random`);
		photos = await res.json();
		img = photos.message;
        });

onMount(() => {
    document.getElementById("cadastroModal").style.display = "none";
    document.getElementById("cadastroModal").click();
});

function cadastro(){
    console.log(nome)
    dispatcher('cadastrar', {nome: nome, desc: desc, img: img})
}

</script>
