// React/adota/src/Edicao.js
import React, {useState, useEffect} from 'react';
import { Button, Modal, Form, Col } from 'react-bootstrap';
import PropTypes from "prop-types";
import Store from './Store';


export function minLengthValidation(minLength, value) {
  if (value.trim().length < minLength) {
    return `Este campo requer pelo menos ${minLength} caracteres`
  }
  return null
}

export function requiredValidation(value) {
  if (value.trim() === '') {
    return 'Este campo é obrigatório'
  }
  return null
}

const validate = {
  info: (value) => minLengthValidation(3, value),
  nome: requiredValidation,
}

export default function Edicao(props) {

    const [show, setShow] = useState(props);
    const [nome, setNome] = useState(props.nome);
    const [info, setInfo] = useState(props.info);
    const [id, setID] = useState(props.id);
    const [img, setImg] = useState(props.img);
    const [nameError, setNameError] = useState("");
    const [nameInfo, setNameInfo] = useState("");
    const [valid, setValid] = useState("valido");

    const {callbackFunctionEditar} = props;
  
    const handleClose = () => setShow(false); 

    function sendData () {
      callbackFunctionEditar();
    }

    const {
      updateDog,
    } = Store()

    function handleChange(event) {
        setNome(event.target.value)
        onBlur(event);
    }

    function handleChangeInfo(event) {
        setInfo(event.target.value)
        onBlur(event);
    }

      const handleCadastrou = (event) =>{
         const dog = {"nome": nome, "info": info, "img": img}
         updateDog(dog, id);
         setShow(false);
         sendData();

        } 
      
        function onBlur(event) {
          const value  = event.target.value
          const name  = event.target.name
          const error = validate[name] ? validate[name](value) : null
          
              if(error != null){
                if(name == "nome"){
                  setNameError(error)
                }else if(name == "info"){
                  setNameInfo(error)
                }
              }

              if(error != null){

                setValid("invalido")
  
                }else if(error === null){
                  if(name === "nome" && nameError !== ""){
                    setNameError("");
                  }else if(name === "info" && nameInfo !== ""){
                    setNameInfo("");
                  }
                }
  
                if(nameError === "" && nameInfo === ""){
                  setValid("valido")
                }
        }
        
    return (
      <> 
        <Modal show={show.show} onHide={handleClose}>
          <Modal.Header closeButton>
            <Modal.Title>Edição do Doguinho</Modal.Title>
          </Modal.Header>
          <Modal.Body>
          <Form>
            <Form.Control name = "nome" onChange={handleChange} value={nome} onBlur={onBlur} placeholder={nome} />
            <br/>
            <div className="error" style={{color: "red"}}>{nameError}</div>
            <br/>
            <Form.Group controlId="exampleForm.ControlTextarea1">
            <Form.Control name = "info" onChange={handleChangeInfo} value={info} onBlur={onBlur} as="textarea" rows="5"  placeholder={info}/>
            <br/>
            <div className="error" style={{color: "red"}}>{nameInfo}</div>
            <br/>
            </Form.Group>
          </Form>    
          </Modal.Body>
          <Modal.Footer>
            <Button variant="secondary" onClick={handleClose}>
              Close
            </Button>
            <Button disabled = {valid != "valido"} variant="primary" onClick={handleCadastrou}>
              Editar
            </Button>
          </Modal.Footer>
        </Modal>
      </>
    );
  }

  Edicao.propTypes = {
    show: PropTypes.bool.isRequired,
    nome: PropTypes.string.isRequired,
    info: PropTypes.string.isRequired,
    id: PropTypes.number.isRequired,
    callbackFunctionEditar: PropTypes.func.isRequired,
  };

// Svelte/adota/src/Edicao.svelte
<button type="button" id={modal} class="btn btn-primary" data-toggle="modal" data-target={ExamplemodalT}>
    Launch demo modal
  </button>
  
  <div class="modal fade" id={Examplemodal} tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="display:block">
          <h5 class="modal-title" id="exampleModalLabel">Editar Cachorro</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <div class="form-group">
            <label for="exampleFormControlInput1">Nome</label>
            <input bind:value={nome} type="input"  on:input={checkField('nome',nome)} on:blur={checkField('nome',nome)} class="form-control" id="exampleFormControlInput1" placeholder="Insira o nome">
            <div class="error" style="color:red">{ nameError }</div>
          </div>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Descrição</label>
            <textarea on:blur={checkField('desc',desc)} on:input={checkField('desc',desc)} bind:value={desc} class="form-control" id="exampleFormControlTextarea1" rows="5" placeholder="Fale sobre ele"></textarea>
          </div>
          <div class="error" style="color:red">{ nameInfo }</div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" on:click={editar} disabled = {valid != "valido"} data-dismiss="modal">Editar</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
import { onMount } from 'svelte';
import { createEventDispatcher } from 'svelte'
import { Store } from './Store.js'

let functions = Store()

const validate = {
  desc: (value) => minLengthValidation(3, value),
  nome: requiredValidation
}

export function minLengthValidation(minLength, value) {
  if (!value || value.trim().length < minLength) {
    return `Este campo requer pelo menos ${minLength} caracteres`
  }
  return null
}

export function requiredValidation(value) {
  if (!value || value.trim() === '') {
    return 'Este campo é obrigatório'
  }
  return null
}

export let nome;
export let img;
export let desc;
export let index;

let nameError = "";
let nameInfo = "";

let valid = "valido"

let photos;

 let modal = "modalEdicaomodal" + index;
 let Examplemodal = "Edicaomodal" + index;
 let ExamplemodalT = "#Edicaomodal" + index;
 const dispatcher = createEventDispatcher()

onMount(() => {
    document.getElementById(modal).style.display = "none";
    document.getElementById(modal).click();
});

function editar(){
    console.log(desc)
    let dog = {nome: nome, info: desc, img: img};
    functions.change(dog, index)
}

function checkField(name, valueCamp) {
        const value = valueCamp;
        const error = validate[name] ? validate[name](value) : null        
              if(error != null){
                if(name == "nome"){
                  nameError = error;
                }else if(name == "desc"){
                  nameInfo = error;
                }
              }

              if(error != null){

                valid = "invalido";

              }else if(error == null){
                if(name == "nome" && nameError != ""){
                  nameError = "";
                }else if(name == "desc" && nameInfo != ""){
                  nameInfo = "";
                }
              }

              if(nameError == "" && nameInfo == ""){
                valid = "valido";
              }
          console.log(valid)

    }

</script>
