// Angular/adota/src/app/cards/cards.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-cards',
  templateUrl: './cards.component.html',
  styleUrls: ['./cards.component.scss']
})
export class CardsComponent implements OnInit {

  @Input() nome: string
  @Input() desc: string
  @Input() url: string
  @Input() index: string
  @Output() delete: EventEmitter<any> = new EventEmitter<any>();

  show = false;

  showModal(){
    this.show = !this.show;
  }
  
  constructor() { }

  ngOnInit(): void {

  }

  remover(date: any):void {
    this.delete.emit(date);
  }

}

<div class="card" style="width: 18rem;">
    <img [src]="url" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{nome}}</h5>
      <p class="card-text">{{desc}}</p>
      <a class="btn btn-primary" (click)="showModal()">Ver informações</a>
    </div>

    <div *ngIf="show === true">
      <app-info [nome] = "nome" [index] = "index" [desc]="desc" (adotar)="remover($event)"></app-info>
    </div>
</div>

// React/adota/src/Cards.js
import './App.css';
import { Button, Card } from 'react-bootstrap';
import React from 'react';
import Details from './Details';

export default class Cards extends React.Component {

  state = {
    show: false
  };
  showModal = e => {
    this.setState({
      show: !this.state.show
    });
  };

  sendData = (e) => {
    this.props.parentCallback(e);
  }
    render() {
      return (
        <div>
          <Card style={{width: '18rem'}}>
          <Card.Img variant="top" src={this.props.img} />
          <Card.Body>
            <Card.Title>{this.props.nome}</Card.Title>
            <Card.Text>
              {this.props.info}
            </Card.Text>
            <Button  onClick={e => {
              this.showModal();
         }}
          > Ver Informações </Button>
          </Card.Body>
          </Card>
          { this.state.show == true ?
          <Details show={this.state.show}
          nome={this.props.nome}
          id={this.props.id}
          info={this.props.info}
          adotou={this.sendData}/>
          : null
          }
        </div>
      )
    }
  }
