// Angular/adota/src/app/store.ts
import { Injectable } from '@angular/core'

@Injectable({
    providedIn: 'root'  // define como global
  })

  export class Store {
    dogs = []
  
     createDog (nome, info, img) {
        let dogsAux = this.dogs;
        dogsAux.push({"nome": nome, "info": info, "img": img});
        this.dogs = dogsAux;
      }
    
      updateDog (dog, index){
        let aux = this.dogs;
        aux[index] = dog;
        this.dogs = aux;
      }
    
      deleteDog(index) {
        const aux = this.dogs;
        aux.splice(index, 1);
        this.dogs = aux; 
      }
    
  }

// React/adota/src/Store.js
import {useState, useEffect} from 'react';

var dogs = [];

export default function Store() {

  const createDog = (nome, info, img) => {
    let dogsAux = dogs;
    dogsAux.push({"nome": nome.value, "info": info.value, "img": img});
    dogs = dogsAux;
  }

  const updateDog = (dog, index) => {
    let aux = dogs;
    aux[index] = dog;
    dogs = aux;
  }

  const deleteDog = (index) => {
    const aux = dogs;
    aux.splice(index, 1);
    dogs = aux; 
  }

  return { dogs, createDog, updateDog, deleteDog }
}
