// Svelte/adota/src/Cadastro.svelte
<button type="button" id="cadastroModal" class="btn btn-primary" data-toggle="modal" data-target="#cModal">
    Launch demo modal
  </button>
  
  <div class="modal fade" id="cModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="display:block">
          <h5 class="modal-title" id="exampleModalLabel">Cadastrar Cachorro</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <div class="form-group">
            <label for="exampleFormControlInput1">Nome</label>
            <input bind:value={nome} type="input" on:blur={checkField('nome',nome)} class="form-control" id="exampleFormControlInput1" placeholder="Insira o nome">
            <div class="error" style="color:red">{ nameError }</div>
          </div>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Descrição</label>
            <textarea on:blur={checkField('desc',desc)} bind:value={desc} class="form-control" id="exampleFormControlTextarea1" rows="5" placeholder="Fale sobre ele"></textarea>
          </div>
          <div class="error" style="color:red">{ nameInfo }</div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" on:click={cadastro} disabled = {valid != "valido"} data-dismiss="modal">Cadastrar</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
import { onMount } from 'svelte';
import { createEventDispatcher } from 'svelte'

const validate = {
  desc: (value) => minLengthValidation(3, value),
  nome: requiredValidation
}

export function minLengthValidation(minLength, value) {
  if (!value || value.trim().length < minLength) {
    return `Este campo requer pelo menos ${minLength} caracteres`
  }
  return null
}

export function requiredValidation(value) {
  if (!value || value.trim() === '') {
    return 'Este campo é obrigatório'
  }
  return null
}

export let nome = ""
export let desc = ""

let nameError = " ";
let nameInfo = " ";

let valid = "invalido"

let photos;
let img;

 const dispatcher = createEventDispatcher()

 onMount(async () => {
		const res = await fetch(`https://dog.ceo/api/breeds/image/random`);
		photos = await res.json();
		img = photos.message;
        });

onMount(() => {
    document.getElementById("cadastroModal").style.display = "none";
    document.getElementById("cadastroModal").click();
});

function cadastro(){
    console.log(nome)
    dispatcher('cadastrar', {nome: nome, desc: desc, img: img})
}

function checkField(name, valueCamp) {
        const value = valueCamp;
        const error = validate[name] ? validate[name](value) : null        
              if(error != null){
                if(name == "nome"){
                  nameError = error;
                }else if(name == "desc"){
                  nameInfo = error;
                }
              }

              if(error != null){

                valid = "invalido";

              }else if(error == null){
                if(name == "nome" && nameError != ""){
                  nameError = "";
                }else if(name == "desc" && nameInfo != ""){
                  nameInfo = "";
                }
              }

              if(nameError == "" && nameInfo == ""){
                valid = "valido";
              }
          console.log(valid)

    }

</script>

// Vue/adota/src/components/Cadastro.vue
<template>
    <div>
        <b-modal :ok-disabled="valid != 'valido'" @ok="cadastrar"
         ok-title = "Cadastrar" ref="my-modal" id="modal-1" title="Cadastrar o Doguinho">
            <b-form-group id="input-group-2" label="Nome:" label-for="input-2">
             <b-form-input
                id="input-2"
                v-model="nome"
                required
                placeholder="Nome do Doguinho"
                @blur="checkField('nome')"
                >
                </b-form-input>
                <br/>
            <div class="error" style="color:red">{{ nameError }}</div>
                <br/>
            <label for="textarea">Descrição:</label>
            <b-form-textarea
                id="textarea"
                @blur="checkField('desc')"
                v-model="desc"
                placeholder="Fale Sobre Ele"
                rows="6"
                max-rows="6"
        ></b-form-textarea>
            <br/>
            <div class="error" style="color:red">{{ nameInfo }}</div>
            <br/>
            </b-form-group>
            
        </b-modal>
    </div>
</template>

<script>
import axios from 'axios';

const validate = {
  desc: (value) => minLengthValidation(3, value),
  nome: requiredValidation
}

export function minLengthValidation(minLength, value) {
  if (!value || value.trim().length < minLength) {
    return `Este campo requer pelo menos ${minLength} caracteres`
  }
  return null
}

export function requiredValidation(value) {
  if (!value || value.trim() === '') {
    return 'Este campo é obrigatório'
  }
  return null
}

export default {
  name: 'Cadastro',

  data: function() {
    return {
      current: 0,
      nome: "",
      desc: "",
      img: "",
      erros: 2,
      nameError: " ",
      nameInfo: " ",
      valid: "invalido"
    } 
  },

  methods: {
      showModal() {
        this.$refs['my-modal'].show()
      },
      cadastrar: function() {
        this.$emit("cadastrar", this.nome, this.desc, this.img);
      },
      checkField(name) {
        const value = this._data[name]
        const error = validate[name] ? validate[name](value) : null        

              if(error != null){
                if(name == "nome"){
                  this.nameError = error;
                }else if(name == "desc"){
                  this.nameInfo = error;
                }
              }

        if(error != null){

              this.valid = "invalido";

              }else if(error == null){
                if(name == "nome" && this.nameError != ""){
                  this.nameError = "";
                }else if(name == "desc" && this.nameInfo != ""){
                  this.nameInfo = "";
                }
              }

              if(this.nameError == "" && this.nameInfo == ""){
                this.valid = "valido";
              }
          console.log(this.valid)
      }
    },
  mounted(){
      this.showModal();

    axios.get(`https://dog.ceo/api/breeds/image/random`)
    .then(response => {
      this.img = response.data.message;
    })
    .catch(e => {
      this.errors.push(e)
    })
  }
}
</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.logo {
  margin-top: 1% !important; 
  margin-right: 5% !important;
}

.App{
  text-align: center;
}

.navbar {
  display: block !important;
}

.App-header {
  background-image: linear-gradient(rgba(255,255,255,0.5), rgba(255,255,255,0.5)), url("../assets/banner.jpg");
  background-size: 100%;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  color: black;
}
</style>
